=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/ListaEjerciciosConAtributosDTD/Ejercicio1DTD.dtd
<!ELEMENT hechos_historicos (hecho)*>
<!ELEMENT hecho (fecha)>
	<!ATTLIST hecho descripcion CDATA #IMPLIED>
<!ELEMENT fecha (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/ListaEjerciciosConAtributosDTD/Ejercicio1DTDExterna.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hechos_historicos SYSTEM "Ejercicio1DTD.dtd">

<hechos_historicos>
	<hecho descripcion = "descripcion1">
		<fecha>
			<dia>12</dia>
			<mes>8</mes>
			<año>1981</año>
		</fecha>
	</hecho>
	<hecho descripcion = "descripcion2">
		<fecha>
			<dia>4</dia>
			<mes>9</mes>
			<año>1998</año>
		</fecha>
	</hecho>
	<hecho descripcion = "descripcion3">
		<fecha>
			<dia>4</dia>
			<mes>2</mes>
			<año>2004</año>
		</fecha>
	</hecho>
</hechos_historicos>
