<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_de_futbol [
   <!ELEMENT equipos_de_futbol (equipo)*>
   <!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT ciudad (#PCDATA)>
   <!ELEMENT entrenador (#PCDATA)>
   <!ELEMENT jugadores (jugador)*>
   <!ELEMENT jugador (nombre, nacionalidad)>
      <!ATTLIST jugador posicion CDATA #REQUIRED>
   <!ELEMENT nacionalidad (#PCDATA)>
]>
<equipos_de_futbol>
   <equipo>
      <nombre>Levante</nombre>
      <ciudad>Valencia</ciudad>
      <entrenador></entrenador>
      <jugadores>
         <jugador posicion="portero">
            <nombre>Javier Jiménez</nombre>
            <nacionalidad>española</nacionalidad>
         </jugador>
         <jugador posicion="delantero">
            <nombre>Nong</nombre>
            <nacionalidad>camerunés</nacionalidad>
         </jugador>
      </jugadores>
   </equipo>
   <equipo>
      <nombre>Real Sociedad</nombre>
      <ciudad>San Sebastián</ciudad>
      <entrenador></entrenador>
      <jugadores>
         <jugador posicion="portero">
            <nombre>Claudio Bravo</nombre>
            <nacionalidad>chilena</nacionalidad>
         </jugador>
         <jugador posicion="defensa">
            <nombre>Mikel González</nombre>
            <nacionalidad>española</nacionalidad>
         </jugador>
      </jugadores>
   </equipo>
</equipos_de_futbol>
