=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Clase/Ejemplo_clase_Externo_2.dtd
<!ELEMENT domicilio (calle, numero, piso, letra, ciudad, provincia, escalera)>
	<!ELEMENT calle (#PCDATA)>
	<!ELEMENT numero (#PCDATA)>
	<!ELEMENT piso (#PCDATA)>
	<!ELEMENT letra (#PCDATA)>
	<!ELEMENT ciudad (#PCDATA)>
	<!ELEMENT provincia (#PCDATA)>
	<!ELEMENT escalera EMPTY>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Clase/Ejemplo_clase_Externo_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE domicilio SYSTEM "Ejemplo_clase_Externo_2.dtd">

<domicilio>
	<calle>Paz</calle>
	<numero>54</numero>
	<piso>1Âª</piso>
	<letra>A</letra>
	<ciudad>Manzanares</ciudad>
	<provincia>C.Real</provincia>
	<escalera/>
</domicilio>
