=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejemplo/vivero.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
	<xs:element name ="vivero">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="especie" maxOccurs="3">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"></xs:element>
							<xs:element name="precio">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extesion name="xs:integer">
											<xs:element name="moneda" type="xs:integer" use="optional"/>
										</xs:extesion>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="variedad" type="xs:string"/>
							<xs:element name="origen" type="xs:string"/>
							<xs:element name="color_fruto" type="xs:string" maxOccurs="2"/>
							<xs:element name="otros_datos">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="maduracion" type="xs:string"/>
										<xs:element name="riego" type="xs:string"/>
										<xs:element name="horario" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="fecha" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="siembra" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejemplo/vivero.xml
<?xml version="1.0" encoding="UTF-8"?>
<vivero xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vivero.xsd">

	<especie siembra="2018">
		<nombre> Lilchi </nombre>
		<precio moneda="euro">25</precio>
		<variedad> variedad 1 </variedad>
		<origen> Filipinas </origen>
		<color_fruto> Rojo </color_fruto>
		<color_fruto> Rosa </color_fruto>
		<otros_datos>
			<maduracion> Agosto </maduracion>
			<riego> Diario </riego>
		</otros_datos>
		<fecha/>
	</especie>
	<especie siembra="2017">
		<nombre> Longan </nombre>
		<precio moneda="Libra">15</precio>
		<variedad> variedad 2 </variedad>
		<origen> China </origen>
		<color_fruto> Marron </color_fruto>
		<otros_datos>
			<maduracion> Agosto </maduracion>
			<riego> Diario </riego>
			<horario> Nocturno </horario>
		</otros_datos>
		<fecha/>
	</especie>
	<especie siembra="2016">
		<nombre> Algodon </nombre>
		<precio> 21 </precio>
		<variedad> variedad 3 </variedad>
		<origen> Florida </origen>
		<color_fruto> Blanco </color_fruto>
		<otros_datos>
			<maduracion> Agosto </maduracion>
			<riego> Cada 15 dias </riego>
		</otros_datos>
		<fecha/>
	</especie>
</vivero>
