=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/LISTAEjerciciosSinAtributosDTD/Ejercicio5DTD.dtd
<!ELEMENT Catalogo (CDs_en_oferta)*>
<!ELEMENT CDs_en_oferta (Titulo, Artista, Pais, Compañia_discográfica, Precio, Año_de_publicacion)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Artista (#PCDATA)>
<!ELEMENT Pais (#PCDATA)>
<!ELEMENT Compañia_discográfica (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Año_de_publicacion (#PCDATA)>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/LISTAEjerciciosSinAtributosDTD/Ejercicio5ConDTDExterna.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Catalogo SYSTEM "Ejercicio5DTD.dtd">
<Catalogo>
	<CDs_en_oferta>
		<Titulo>Titulo 1</Titulo>
		<Artista>Artista 1</Artista>
		<Pais>Pais 1</Pais>
		<Compañia_discográfica>Compañia 1</Compañia_discográfica>
		<Precio>10</Precio>
		<Año_de_publicacion>2011</Año_de_publicacion>
	</CDs_en_oferta>
	<CDs_en_oferta>
		<Titulo>Titulo 2</Titulo>
		<Artista>Artista 2</Artista>
		<Pais>Pais 2</Pais>
		<Compañia_discográfica>Compañia 2</Compañia_discográfica>
		<Precio>20</Precio>
		<Año_de_publicacion>2012</Año_de_publicacion>
	</CDs_en_oferta>
	<CDs_en_oferta>
		<Titulo>Titulo 3</Titulo>
		<Artista>Artista 3</Artista>
		<Pais>Pais 3</Pais>
		<Compañia_discográfica>Compañia 3</Compañia_discográfica>
		<Precio>30</Precio>
		<Año_de_publicacion>2013</Año_de_publicacion>
	</CDs_en_oferta>
</Catalogo>
