<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carta [
	<!ELEMENT carta (emisor_del_pedido, receptor_del_pedido, mensaje)>
	<!ELEMENT emisor_del_pedido (#PCDATA)>
	<!ELEMENT receptor_del_pedido (#PCDATA)>
	<!ELEMENT mensaje (saludo, introduccion, cuerpo, desenlace, despedida)>
	<!ELEMENT saludo (#PCDATA)>
	<!ELEMENT introduccion (#PCDATA)>
	<!ELEMENT cuerpo (#PCDATA)>
	<!ELEMENT desenlace (#PCDATA)>
	<!ELEMENT despedida (#PCDATA)>
]>
<carta>
	<emisor_del_pedido>Roberto Sánchez</emisor_del_pedido>
	<receptor_del_pedido>María Sánchez</receptor_del_pedido>
	<mensaje>
		<saludo>Querida María</saludo>
		<introduccion>Lorem ipsum</introduccion>
		<cuerpo>Lorem ipsum</cuerpo>
		<desenlace>Lorem ipsum</desenlace>
		<despedida>Lorem ipsum</despedida>
	</mensaje>
</carta>