=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/Actividades xsd/Ejercicio_Tickets_xsd.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tickets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ticket" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Fecha" type="xs:date"/>
							<xs:element name="Hora" type="xs:time"/>
							<xs:element name="Precio">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Precio_sin_IVA" type="xs:double"/>
										<xs:element name="Precio_con_IVA" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Forma_de_pago">
								<xs:complexType>
									<xs:choice>
										<xs:element name="Con_tarjeta">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="cantidad" type="xs:string"/>
													<xs:element name="numero_de_tarjeta" type="xs:integer"/>
													<xs:element name="Nombre_de_propietario_de_la_tarjeta" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>			
										</xs:element>
										<xs:element name="Efectivo">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="cantidad" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:choice>	
								</xs:complexType>
							</xs:element>	
						</xs:sequence>
						<xs:attribute name="Codigo_de_ticket" type="xs:string"/>
					</xs:complexType>	
				</xs:element>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividades/Ejercicios_Pdfs/Actividades xsd/Ejercicio_Tickets_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="Ejercicio_Tickets_xsd.xsd">

<tickets>
    <ticket Codigo_del_ticket="0483t">
        <Fecha>06/10/2022</Fecha>
        <Hora>17:40</Hora>
        <Precio>
            <Precio_sin_IVA>71 euros</Precio_sin_IVA>
            <Precio_con_IVA>74 euros</Precio_con_IVA>
        </Precio>
        <Forma_de_pago>
            <Con_tarjeta>
                <Cantidad>74 euros</Cantidad>
                <Numero_de_tarjeta>757357283</Numero_de_tarjeta>
                <Nombre_del_propietario_de_la_tarjeta>Antonio Jim√©nez Roncero</Nombre_del_propietario_de_la_tarjeta>
            </Con_tarjeta>
        </Forma_de_pago>
    </ticket>
    <ticket Codigo_del_ticket="0484t">
        <Fecha>06/10/2022</Fecha>
        <Hora>17:45</Hora>
        <Precio>
            <Precio_sin_IVA>21 euros</Precio_sin_IVA>
            <Precio_con_IVA>25 euros</Precio_con_IVA>
        </Precio>
        <Forma_de_pago>
            <Efectivo>
                <Cantidad>25 euros</Cantidad>
            </Efectivo>
        </Forma_de_pago>
    </ticket>
</tickets>
