=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividad Evaluable/MARCAS_UT3_P2_Sergio_Bravo_Mora.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="apodo"/>
				<xs:element name="direcciones">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="direccion" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="calle" type="xs:string"/>
										<xs:element name="numero" type="xs:integer"/>
										<xs:element name="ciudad" type="xs:string"/>
										<xs:element name="escalera" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="numero" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="telefono" type="xs:integer"/>
				<xs:element name="estudios">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo">
								<xs:element name="nombre" type="xs:string"/>
								<xs:element name="centro">
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:string">
												<xs:attribute name="tipo" type="xs:string" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="tipoTitulo" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="idiomas" type="xs:string">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="idioma">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="nivel" use="optional" default="B1">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="A1"/>
														<xs:enumeration value="A2"/>
														<xs:enumeration value="B1"/>
														<xs:enumeration value="B2"/>
														<xs:enumeration value="C1"/>
														<xs:enumeration value="C2"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergiobmnv/Curso-DesarolloWeb/Curso Desarrollo Web 1º/Lenguaje de Marcas/Tema_3/Actividad Evaluable/MARCAS_UT3_P2_Sergio_Bravo_Mora.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="MARCAS_UT3_P2_Sergio_Bravo_Mora.xsd">

    <nombre>Steve Jobs</nombre>
    <apodo/>
    <direcciones> 
        <direccion numero="1">
            <calle>770 de Welch Rd., Ste</calle>
            <numero>154</numero>
            <ciudad>Palo Alto</ciudad>
        </direccion>
        <direccion numero="2">
            <calle>Desengaño</calle>
            <numero>21</numero>
            <ciudad>Madrid</ciudad>
        </direccion>
    </direcciones>
    <telefono>685097256</telefono>
    <email>stevijobs@gmail.com</email>
    <email>eljefedeapple@gmail.com</email>
    <idiomas>
        <idioma>Japones</idioma>
        <idioma nivel="A2">Español</idioma>
        <idioma nivel="B2">Alemán</idioma>
        <idioma nivel="C2">Inglés</idioma>
    </idiomas>
</cv>
